### ISSUE TITLE
BUILD Error NETSDK1147 on Apple M1

### ISSUE THREAD

**Issue by HausBJB** [dotnet/maui-samples#101]
Hello I get the following errors with this command
dotnet build HelloMaui -t:Run -f net6.0-ios

Error:
/usr/local/share/dotnet/sdk/6.0.100-preview.2.21155.3/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(24,5): error NETSDK1147: Die folgenden Workloadpakete wurden nicht installiert: Microsoft.Android.Sdk [/Users//Downloads/net6-mobile-samples-main/HelloMaui/HelloMaui.csproj]

Installed:
SDK 6.0.100-preview.2 (Arm64)
macOS: Microsoft.NET.Workload.Android-11.0.200.148.pkg
macOS: Microsoft.iOS.Bundle.14.4.100-ci.main.1192.pkg
macOS: Microsoft.MacCatalyst.Bundle.14.3.100-ci.main.337.pkg

System:
MacBook Pro 2020 (M1)
Visual Studio 2019
Xcode 12.4

**Comment by jonathanpeppers** [comment]
You can add this line locally to get further:

https://github.com/xamarin/xamarin-android/blob/304e698966a16cf2af992b3a24cb0323f561c31c/src/Xamarin.Android.Build.Tasks/Microsoft.NET.Workload.Android/WorkloadManifest.in.json#L20

However, we still have some native libraries that aren't built for M1, so you'll still hit further issues.

**Comment by HausBJB** [comment]
Ok, thank you first that didn't help, then we'll wait as soon as it works

**Comment by jonathanpeppers** [comment]
Related:
* https://github.com/xamarin/LibZipSharp/pull/84
* https://github.com/mono/mono.posix

The two files we need for M1 are `libzip.dylib` and `libMonoPosixHelper.dylib`.

**Comment by lihuiniu** [comment]
@jonathanpeppers I faced the same issue but for macos:

/usr/local/share/dotnet/sdk/6.0.100-preview.2.21155.3/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(24,5) : error NETSDK1147: The following workload packs were not installed: Microsoft.macOS.Sdk
Unable to create package spec for project. 

I installed .net6 preview 4 and maui-check formerly without add maui-check to pathvariable so I could not find maui-check command available for me, then tried to "dotnet tool uninstall -g Redth.Net.Maui.Check" not working, 
"dotnet tool update -g Redth.Net.Maui.Check" also not working.

So I removed .net preview 4 and re-install .net6 preview 2 instead, however I got the above exception when load any MacOS Native app.

**Comment by lihuiniu** [comment]
Fixed by install workload for macos:
sudo dotnet workload install microsoft-macos-sdk-full --skip-manifest-update
reference: 
https://github.com/dotnet/maui-samples#dotnet-workload-install-command

sudo dotnet workload install microsoft-macos-sdk-full --skip-manifest-update
