### ISSUE TITLE
[MAUI] Crash when running on a simulator with Google Play Store enabled

### ISSUE THREAD

**Issue by DevEddy** [dotnet/maui-samples#104]
Hi there, 

I tried the MAUI sample on Android API29 and API30 with and without store. The crash happens only when MAUI is running on Android emulator with Google Play Store enabled. Without Google Play Store everything works as expected. 

```
03-18 09:36:57.633  4982  4982 I MonoDroid:   --- End of managed Java.Lang.ArrayIndexOutOfBoundsException stack trace ---
03-18 09:36:57.633  4982  4982 I MonoDroid: java.lang.ArrayIndexOutOfBoundsException: length=23; index=-4
03-18 09:36:57.633  4982  4982 I MonoDroid:     at android.text.StaticLayout.getLineTop(StaticLayout.java:1213)
```

I've attached two logs which I got via catlog. 

[MAUI_crash_api30_withstore_pixel3a.log](https://github.com/dotnet/net6-mobile-samples/files/6162488/MAUI_crash_api30_withstore_pixel3a.log)
[MAUI_crash_api29_withstore_pixel.log](https://github.com/dotnet/net6-mobile-samples/files/6162490/MAUI_crash_api29_withstore_pixel.log)

Any idea?

PS: The native Xamarin.Android project doesn't crash at all.

- Eddy

**Comment by jonathanpeppers** [comment]
Someone else was hitting this and changed the version of Microsoft.Maui to `6.0.100-preview.2.148` and it worked around the issue.

Does that work for you?

**Comment by DevEddy** [comment]
Hi @jonathanpeppers ,

I am sorry, I didn't see that someone had this issue before.
Setting Microsoft.Maui to `6.0.100-preview.2.148` worked for me, too!

**Comment by jonathanpeppers** [comment]
We can keep this open, it was someone at Microsoft, so it wasn't a public Github issue.

**Comment by jonathanpeppers** [comment]
I don't think this is an issue in the latest preview, can you try Preview 5 and let us know, thanks!

https://devblogs.microsoft.com/dotnet/announcing-net-maui-preview-5/
