### ISSUE TITLE
"System.Xml.XmlException: Root element is missing" when trying to run the application

### ISSUE THREAD

**Issue by Thorstensen** [dotnet/maui-samples#109]
Hi.

I just cloned the repo and followed the steps to run the `HelloMaui` project, but always ends up with the following error:

```
You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.osx-x64/11.0.200-ci.main.148/tools/Xamarin.Android.Tooling.targets(64,5): error XARSD7000: System.Xml.XmlException: Root element is missing.
```
**My setup:**
 * macOS Big Sur 11.2.1
 * Visual Studio Code 1.54.3
 * .NET Version 6.0.100-preview.2.21155.3

I´ve also installed the iOS and android workloads

**Steps to reproduce:**
1) Clone the repository
2) Open the workspace in VSCode `code net6-mobile-samples.code-workspace`
3) Open the Command Palette for `Run Build Task` and select `Build`
4) Select HelloMaui/HelloMaui.csproj 
5) Select `Build`
6) Select `Debug`

This also occured when trying to build it from the terminal by writing:

 `dotnet build HelloMaui -t:Run -f net6.0-android --no-restore`

Removing the `--no-restore` results in:

`error MSB4057: The target "Run" does not exist in the project.`

Any suggestions that might get this example up and running?

**Comment by Redth** [comment]
You might need VSMac installed for now in the previews.

Could you update to the latest (P3) and try again please?
