### ISSUE TITLE
MAUI: Add multi page sample

### ISSUE THREAD

**Issue by FakiExx** [dotnet/maui-samples#117]
It would be really helpful if the HelloMaui sample could be extended to have multiple pages.

I was testing out the HellMaui sample and everything works fine so far. I can run the project on iOS, Android and Mac, I can create ViewModels, bind them to my ContentPage (Basically everything that I'm used to from Xamarin.Forms.) and so on.

However I'm having trouble when it comes to the navigation between pages. The workflow seems to have changed quiet a bit, now that Windows are used. In Xamarin.Forms I could just set the MainPage to be a NavigationPage and I was good to go. Now I'm a bit lost on how to implement similar behavior. Simply changing the IPage during runtime in the Window that is being created on startup does not seem to have any effect.

Would be nice if someone could help me out and point me in the right direction or give me a small example on how I should approach the navigation in MAUI.

Best Regards

**Comment by vfongmala** [comment]
Anyone found the solution for navigation yet?

**Comment by FakiExx** [comment]
Hi there,

for anyone having a similar problem, have a look at the linked repository:

https://github.com/davidortinau/WeatherTwentyOne

It's a weather app implemented using Maui and it already contains navigation. Basically the CreateWindow function needs to contain something similar to this:

```
return new Window(
    new NavigationPage(
        new HomePage()
    )
);
```

Since I believe that it is still a good idea to have multiple pages in the official samples I leave the issue open for now.

**Comment by chucker** [comment]
But neither `NavigationPage` nor `HomePage` is a `MultiPage`.

With XamForms, I could simply have:

```csharp
        public App()
        {
            InitializeComponent();

            MainPage = new MainPage();
        }
```

and have `MainPage` inherit from `TabbedPage`.

With MAUI, `MainPage` apparently also has to implement `IPage`. It's unclear to me how to implement the `IPage.View` property in a way that work with a multi page such as `TabbedPage`.
