### ISSUE TITLE
Reference errors in xaml

### ISSUE THREAD

**Issue by DaniSpiI** [dotnet/maui-samples#137]
Hi everyone, 
I can successfully build the HelloWinUI3 in VisualStudio and HelloAndroid but I get this errors in the xaml. The project runs, but since I do not see the proper assembly I cannot try some other things or have to guess but still get error after wards. 
I cloned the latest version of the solution and ran the maui check (that gives me green light ;))

![MAUI_Xaml_ReferenceError](https://user-images.githubusercontent.com/74406316/115506262-f4b2cb00-a27a-11eb-91fe-e23a7c31db32.jpg)

![MAUI_Xaml_ReferenceError1](https://user-images.githubusercontent.com/74406316/115506943-c4b7f780-a27b-11eb-8402-0df428a16fc6.jpg)

![MAUI_Xaml_ReferenceError2](https://user-images.githubusercontent.com/74406316/115506949-c4b7f780-a27b-11eb-9724-24712f7dd729.jpg)

![MAUI_Xaml_ReferenceError3](https://user-images.githubusercontent.com/74406316/115506952-c5508e00-a27b-11eb-9294-96e22a83dfca.jpg)

Does anyone have this problem or/and know how to solve it?

Thanks!
Dani

**Comment by MauRiEEZZZ** [comment]
I have the same "problem" I was testing HotReload and that was not working for me and I stumbled upon these squiggly lines in MainPage.xml.

**Comment by chucker** [comment]
I believe IDEs need updates for XAML editing to work. (Maybe next week’s Build conference will provide some clarity.)

Also: did you clone main, or develop?

**Comment by chucker** [comment]
[16.11 preview 1 adds Maui support.](https://devblogs.microsoft.com/visualstudio/visual-studio-2019-v16-10-and-v16-11-preview-1-are-available-today/#net-maui), so maybe that fixes XAML!

**Comment by MauRiEEZZZ** [comment]
Thanks!
Sorry for the late answer, I was running 16.10.0 Preview 2.1
I believe I did that according some guidance somewhere here on Github.
I will install 16.11 P1 and will report back.

**Comment by sergiojrdotnet** [comment]
Works fine here on VS 16.11 P1
