### ISSUE TITLE
I can't run HelloMaui project on my android phone

### ISSUE THREAD

**Issue by sergiojrdotnet** [dotnet/maui-samples#146]
![TargetFramework](https://user-images.githubusercontent.com/72770006/116817183-8fdd5780-ab3b-11eb-99f5-95ad3058173d.png)

![TargetFramework](https://user-images.githubusercontent.com/72770006/116817202-9f5ca080-ab3b-11eb-841d-343c699b3b69.png)

Instead, HelloAndroid works fine!

**Comment by jonathanpeppers** [comment]
Maybe @tondat can help.

**Comment by jonathanpeppers** [comment]
Can you try again with the new releases that came out yesterday? Thanks!

* https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview
* https://devblogs.microsoft.com/dotnet/announcing-net-maui-preview-5/

I believe the issue you're seeing here might be fixed.
