### ISSUE TITLE
System.Reflection.TargetInvocationException   HResult=0x80131604

### ISSUE THREAD

**Issue by Daniellled** [dotnet/maui-samples#149]
I have a freshly created Windows 10 VM and when I attempt to run the HelloWinUI3.sln I receive a System.Reflection.TargetInvocationException.

**Windows 10 Version:** Microsoft Windows [Version 10.0.19042.985]
**Dotnet SDK version:** 6.0.100-preview.3.21202.5 [C:\Program Files\dotnet\sdk]
**Visual Studio Version:** Microsoft Visual Studio Enterprise 2019 Preview Version 16.10.0 Preview 4.0
**Maui-check response:**  Congratulations, everything looks great!

> System.Reflection.TargetInvocationException
>   HResult=0x80131604
>   Message=Exception has been thrown by the target of an invocation.
>   Source=System.Private.CoreLib
>   StackTrace:
>    at System.RuntimeType.CreateInstanceOfT()
>    at System.Activator.CreateInstance[T]()
>    at WinRT.WeakLazy`1.get_Value()
>    at Microsoft.UI.Xaml.Application._IApplicationStatics.get_Instance()
>    at Microsoft.UI.Xaml.Application.Start(ApplicationInitializationCallback callback)
>    at HelloWinUI3.Program.Main(String[] args) in C:\Users\Bob\Documents\Code\net6-mobile-samples\HelloWinUI3\HelloWinUI3\obj\x64\Debug\net6.0-windows10.0.19041.0\App.g.i.cs:line 26
> 
>   This exception was originally thrown at this call stack:
>     [External Code]
> 
> Inner Exception 1:
> COMException: Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
>

**Comment by mjfusa** [comment]
I'm also hitting this issue. Used maui-check to install tools and VS 16.11.0 Preview 1.

**Comment by KanniyappanP** [comment]
I'm also having this issue in VS 16.11.0 P1

**Comment by jaredthirsk** [comment]
I am getting this with 6.0.100-preview.4.21255.9 and VS 16.11.0 Preview 1.0.  maui-check says everything's ok.

**Comment by alexander-yozzo** [comment]
Same here, passing maui-check
Microsoft Visual Studio Community 2019 Preview
Version 16.11.0 Preview 1.0

**Comment by u2m4c6** [comment]
Same here and same setup as Alexander. Has anyone been able to work around this?

**Comment by kartik786-git** [comment]
why this issue and what is solution

**Comment by bhokareprasad** [comment]
I recently started with MAUI and ran into this.

**Comment by Darkatek7** [comment]
Same issue on my side

**Comment by akimusume** [comment]
Same with VS2022. The maui-check says "Android SDK" and ".NET SDK - Workloads(5 parts about android and ios)" are missing. But I am running it on Windows.
