### ISSUE TITLE
MAUI Blazor project doesn't run on the profile Android Emulator

### ISSUE THREAD

**Issue by comfycoder** [dotnet/maui-samples#157]
I have a fresh install of Visual Studio 2019 16.11.0 Preview 1.0
maui-check reports everything looks good

I created a new MAUI Blasor app.

The app builds ok, but I get the following error:

![image](https://user-images.githubusercontent.com/18965312/120120159-2d3ea200-c161-11eb-8a0d-d3f34ea2a483.png)

The following is my build output:

Build started...
Starting emulator pixel_3a_xl_r_11_0_-_api_30 ...
1>------ Build started: Project: MauiBlazorApp, Configuration: Debug Any CPU ------
C:\Program Files (x86)\Android\android-sdk\emulator\emulator.EXE -no-boot-anim -avd pixel_3a_xl_r_11_0_-_api_30 -prop monodroid.avdname=pixel_3a_xl_r_11_0_-_api_30
1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
1>Executing SayHello Task to establish a connection to a Remote Server. 
1>			Properties: 
1>				SessionId=c135e47bb1a154a39597340e670832779022756061a3269c117c0d6d1c51bde9, 
1>				ServerPort=, 
1>				ServerAddress=, 
1>				ServerUser=, 
1>				ServerPassword=, 
1>				SSHKey=, 
1>				SSHPassPhrase=,
1>				AppName=MauiBlazorApp,
1>				VisualStudioProcessId=3920,
1>				ContinueOnDisconnected=true
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\14.5.100-preview.4.638\tools\msbuild\iOS\Xamarin.Messaging.Build.targets(107,3): warning VSX1000: Not enough information has been provided to MSBuild in order to establish a connection to a Remote Server. The project 'MauiBlazorApp' will continue building offline
1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\11.0.200-preview.4.245\tools\Xamarin.Android.Common.targets(424,3): warning XA0119: Using fast deployment and AOT at the same time is not recommended. Use fast deployment for Debug configurations and AOT for Release configurations.
1>wwwroot\css\app.css : warning XA0101: @(Content) build action is not supported
1>wwwroot\css\bootstrap\bootstrap.min.css : warning XA0101: @(Content) build action is not supported
1>wwwroot\css\bootstrap\bootstrap.min.css.map : warning XA0101: @(Content) build action is not supported
1>wwwroot\css\open-iconic\FONT-LICENSE : warning XA0101: @(Content) build action is not supported
1>wwwroot\css\open-iconic\font\css\open-iconic-bootstrap.min.css : warning XA0101: @(Content) build action is not supported
1>wwwroot\css\open-iconic\font\fonts\open-iconic.eot : warning XA0101: @(Content) build action is not supported
1>wwwroot\css\open-iconic\font\fonts\open-iconic.otf : warning XA0101: @(Content) build action is not supported
1>wwwroot\css\open-iconic\font\fonts\open-iconic.svg : warning XA0101: @(Content) build action is not supported
1>wwwroot\css\open-iconic\font\fonts\open-iconic.ttf : warning XA0101: @(Content) build action is not supported
1>wwwroot\css\open-iconic\font\fonts\open-iconic.woff : warning XA0101: @(Content) build action is not supported
1>wwwroot\css\open-iconic\ICON-LICENSE : warning XA0101: @(Content) build action is not supported
1>wwwroot\css\open-iconic\README.md : warning XA0101: @(Content) build action is not supported
1>wwwroot\index.html : warning XA0101: @(Content) build action is not supported
1>MauiBlazorApp -> C:\srcMAUI\MauiBlazorApp\MauiBlazorApp\MauiBlazorApp\bin\Debug\net6.0-maccatalyst\maccatalyst-x64\MauiBlazorApp.dll
1>MauiBlazorApp -> C:\srcMAUI\MauiBlazorApp\MauiBlazorApp\MauiBlazorApp\bin\Debug\net6.0-android\MauiBlazorApp.dll
1>Done building project "MauiBlazorApp.csproj".
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\14.5.100-preview.4.638\tools\msbuild\iOS\Xamarin.Messaging.Build.targets(107,3): warning VSX1000: The connection to the Mac Server with Address='' and User='' couldn't be established. The project 'MauiBlazorApp' will continue building offline
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\14.5.100-preview.4.638\tools\msbuild\iOS\Xamarin.Messaging.Apple.targets(31,3): warning : There is no available connection to the Mac. Task 'VerifyXcodeVersion' will not be executed
1>MauiBlazorApp -> C:\srcMAUI\MauiBlazorApp\MauiBlazorApp\MauiBlazorApp\bin\Debug\net6.0-ios\iossimulator-x64\MauiBlazorApp.dll
1>Done building project "MauiBlazorApp.csproj".
2>------ Deploy started: Project: MauiBlazorApp, Configuration: Debug Any CPU ------
2>Waiting for the emulator is ready...
Emulator pixel_3a_xl_r_11_0_-_api_30 is running.
2>Starting deployment to pixel_3a_xl_r_11_0_-_api_30 ...
2>Deploying to pixel_3a_xl_r_11_0_-_api_30 ...
Build started.
Project "MauiBlazorApp.csproj" (Install target(s)):
You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
There is no application host available for the specified RuntimeIdentifier 'android-x86'.
Found Java SDK version 1.8.0.
Found Java SDK version 1.8.0.
Dex Fast Deployment Enabled: False
MonoAndroid Tools: C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\11.0.200-preview.4.245\tools\
Android Platform API level: 30
TargetFrameworkVersion: v6.0
Android NDK: 
Android SDK: C:\Program Files (x86)\Android\android-sdk\
Android SDK Build Tools: C:\Program Files (x86)\Android\android-sdk\build-tools\30.0.2\
Java SDK: C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25\
Application Java class: android.app.Application
Skipping target "ProcessMauiSplashScreens" because all output files are up-to-date with respect to the input files.
Skipping target "ProcessMauiFonts" because all output files are up-to-date with respect to the input files.
Skipping target "ResizetizeImages" because all output files are up-to-date with respect to the input files.
Skipping target "_ResolveLibraryProjectImports" because all output files are up-to-date with respect to the input files.
Skipping target "_BuildLibraryImportsCache" because all output files are up-to-date with respect to the input files.
Skipping target "_GenerateAndroidResourceDir" because all output files are up-to-date with respect to the input files.
Skipping target "_GenerateLayoutBindings" because it has no outputs.
Skipping target "_ConvertResourcesCases" because all output files are up-to-date with respect to the input files.
Skipping target "_CompileResources" because all output files are up-to-date with respect to the input files.
Skipping target "_PrepareUpdateAndroidResgen" because all output files are up-to-date with respect to the input files.
Skipping target "_UpdateAndroidResgen" because all output files are up-to-date with respect to the input files.
Skipping target "_GenerateEmbeddedFilesManifest" because all output files are up-to-date with respect to the input files.
Project "MauiBlazorApp.csproj" (_ComputeFilesToPublishForRuntimeIdentifiers target(s)):
Done building project "MauiBlazorApp.csproj".
Project "MauiBlazorApp.csproj" (_ComputeFilesToPublishForRuntimeIdentifiers target(s)):
Done building project "MauiBlazorApp.csproj".
Skipping target "_LinkAssembliesNoShrink" because all output files are up-to-date with respect to the input files.
Skipping target "_GenerateJavaStubs" because all output files are up-to-date with respect to the input files.
Skipping target "_ManifestMerger" because all output files are up-to-date with respect to the input files.
Skipping target "_ConvertCustomView" because all output files are up-to-date with respect to the input files.
Skipping target "_AddStaticResources" because all output files are up-to-date with respect to the input files.
Skipping target "_GeneratePackageManagerJava" because all output files are up-to-date with respect to the input files.
Skipping target "_GenerateAndroidAssetsDir" because all output files are up-to-date with respect to the input files.
Skipping target "_PrepareCreateBaseApk" because all output files are up-to-date with respect to the input files.
Skipping target "_CreateBaseApk" because all output files are up-to-date with respect to the input files.
Skipping target "_CompileJava" because all output files are up-to-date with respect to the input files.
Skipping target "_CompileNativeAssemblySources" because all output files are up-to-date with respect to the input files.
Skipping target "_CreateApplicationSharedLibraries" because all output files are up-to-date with respect to the input files.
Skipping target "_CompileToDalvik" because all output files are up-to-date with respect to the input files.
Skipping target "_BuildApkFastDev" because all output files are up-to-date with respect to the input files.
Skipping target "_CopyPackage" because all output files are up-to-date with respect to the input files.
Touching "obj\Debug
et6.0-android\android_debug_keystore.flag".
Skipping target "_Sign" because all output files are up-to-date with respect to the input files.
Skipping target "_Upload" because all output files are up-to-date with respect to the input files.
Done building project "MauiBlazorApp.csproj".
Build succeeded.
2>Deployment was successful to pixel_3a_xl_r_11_0_-_api_30.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 1 succeeded, 0 failed, 0 skipped ==========

I also had the following warning output:

Severity	Code	Description	Project	File	Line	Suppression State
Warning	XA0119	Using fast deployment and AOT at the same time is not recommended. Use fast deployment for Debug configurations and AOT for Release configurations.	MauiBlazorApp	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\11.0.200-preview.4.245\tools\Xamarin.Android.Common.targets	424	

Any ideas on this issue and a way to resolve it?

**Comment by jonathanpeppers** [comment]
I believe this was a bug in VS 16.11 Preview 1, Preview 2 just came out :

https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview

Can you try and let us know if you hit an issue? Thanks.
