### ISSUE TITLE
Can't run from VS for Mac

### ISSUE THREAD

**Issue by ncarandini** [dotnet/maui-samples#158]
Hi, I can run the MAUI sample from my MacBook Pro CLI with the `dotnet build HelloMaui -t:Run -f net6.0-ios` command:

![image](https://user-images.githubusercontent.com/139274/120121095-e2914a00-c1a1-11eb-96ce-c7f61d03e852.png)

but from VS for Mac I get errors:

![image](https://user-images.githubusercontent.com/139274/120121242-9eeb1000-c1a2-11eb-8441-ec0a95d9164e.png)

Is something "On my Mac" or VS for Mac is still not ready to support MAUI in .NET 6  Preview 4 ?

**Comment by VladislavAntonyuk** [comment]
VS4Mac is not ready for the MAUI yet.

**Comment by jonathanpeppers** [comment]
Yes, VS for Mac can't run .NET 6 projects yet: https://github.com/dotnet/maui-samples#visual-studio-for-mac

**Comment by ncarandini** [comment]
Ops, I've missed that info, thanks a lot.
