### ISSUE TITLE
How to choose the iOS simulator?

### ISSUE THREAD

**Issue by ncarandini** [dotnet/maui-samples#159]
Hi folks,
Is there a way to ask for a specific iOS simulator when using the CLI command to run the project?

As an example, when running the `dotnet build HelloMaui -t:Run -f net6.0-ios` command from the CLI, the iPad Pro simulator is started.

Is there a way to set it to a different model (i.e. iPhone 12) ?

**Comment by rolfbjarne** [comment]
Yes, there is: https://github.com/dotnet/xamarin/issues/26#issuecomment-757981580 (it's not very user-friendly at the moment, but it will be improved in a later release).
