### ISSUE TITLE
Samples Dead on Arrival VS For Mac 8.10 Build 1773 (.Net 6 Preview 4)

### ISSUE THREAD

**Issue by BicycleMark** [dotnet/maui-samples#161]
Hello:
  I am VS for Mac Preview Channel. I have VS 4 Mac ver 8.10 1773. When i open up net6-samples.sln and build i only get:
uilding HelloiOS (Debug)

Build started 6/5/2021 5:59:18 PM.
/usr/local/share/dotnet/sdk/6.0.100-preview.4.21255.9/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.props(14,38): error MSB4236: The SDK 'Microsoft.NET.SDK.WorkloadAutoImportPropsLocator' specified could not be found.

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.04

========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Build: 1 error, 0 warnings

**Comment by VladislavAntonyuk** [comment]
First thing first, VS 4 Mac is not ready for Maui. 
Second thing second, run Maui-check and fix all issues

**Comment by jonathanpeppers** [comment]
@BicycleMark if you build at the command line does it work?

```
dotnet build HelloiOS -bl
```

If that doesn't work, can you share the `msbuild.binlog` file that `-bl` creates? thanks!

**Comment by jonathanpeppers** [comment]
Closing for nowj, let us know if you can share more info. Preview 5 just came out, so maybe you'll have better luck using that, thanks.
