### ISSUE TITLE
Is the the HelloMauiWinUI3 working on Visual Studio 2019 Preview 16.11.0 Preview 1.0?

### ISSUE THREAD

**Issue by anaselhajjaji** [dotnet/maui-samples#170]
Steps to reproduce:

Using Visual Studio:

![image](https://user-images.githubusercontent.com/3309485/122274131-37c2a080-ceb0-11eb-8afe-637e8eefd8b9.png)

I opened HelloMauiWinUI3.sln

I have some nuget packages issues on HelloMauiWinUI3 (package project)

![image](https://user-images.githubusercontent.com/3309485/122274300-6771a880-ceb0-11eb-89bb-14c8849e541d.png)

If I try to run the app, I have the following error:

![image](https://user-images.githubusercontent.com/3309485/122274387-7e17ff80-ceb0-11eb-9835-fd5c6906d525.png)

**Comment by VladislavAntonyuk** [comment]
yes, you have to run HelloMauiWinUI3 (Package) instead of HelloMauiWinUI3

**Comment by anaselhajjaji** [comment]
I changed the startup project but I have the same error.

**Comment by jonathanpeppers** [comment]
@anaselhajjaji have you tried Preview 5 which just came out yesterday?

They removed one of the extra WinUI projects, and there are now two VS extensions you need to install:

https://devblogs.microsoft.com/dotnet/announcing-net-maui-preview-5/#single-project-templates-updates

**Comment by anaselhajjaji** [comment]
@jonathanpeppers I just tried Preview 5, it's working I will close the issue.
