### ISSUE TITLE
An item with the same key has already been added. Key: microsoft-android-sdk-full

### ISSUE THREAD

**Issue by lokinfey** [dotnet/maui-samples#174]
I update to .NET 6 preview 5 in MacBook .

but when I run dotnet tool update --global Redth.Net.Maui.Check
it show me this error:

/var/folders/rt/xqzgzfjd1bvcq4r7tw_vdpqc0000gn/T/bouisozj.tf5/restore.csproj(5,3): warning MSB4242: The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed to run. An item with the same key has already been added. Key: microsoft-android-sdk-full
/usr/local/share/dotnet/sdk/6.0.100-preview.5.21302.13/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.props(14,3): warning MSB4242: The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed to run. An item with the same key has already been added. Key: microsoft-android-sdk-full
/usr/local/share/dotnet/sdk/6.0.100-preview.5.21302.13/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.props(14,38): error MSB4236: The SDK 'Microsoft.NET.SDK.WorkloadAutoImportPropsLocator' specified could not be found. [/var/folders/rt/xqzgzfjd1bvcq4r7tw_vdpqc0000gn/T/bouisozj.tf5/restore.csproj]
Tool 'redth.net.maui.check' failed to update due to the following:
The tool package could not be restored.
Tool 'redth.net.maui.check' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by jonathanpeppers** [comment]
Can you try the workaround in [known issues](https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md#preview-5)?

> In the .NET SDK installation folder, delete all folders under sdk-manifests\6.0.100 (for example, under C:\Program Files\dotnet\sdk-manifests\6.0.100) that have the form Microsoft.NET.Workload.*, EXCEPT for microsoft.net.workload.mono.toolchain

You probably need to manually delete: `/usr/local/share/dotnet/sdk-manifests/6.0.100/Microsoft.NET.Workload.Android`

**Comment by TanayParikh** [comment]
> Can you try the workaround in [known issues](https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md#preview-5)?
> 
> > In the .NET SDK installation folder, delete all folders under sdk-manifests\6.0.100 (for example, under C:\Program Files\dotnet\sdk-manifests\6.0.100) that have the form Microsoft.NET.Workload.*, EXCEPT for microsoft.net.workload.mono.toolchain
> 
> You probably need to manually delete: `/usr/local/share/dotnet/sdk-manifests/6.0.100/Microsoft.NET.Workload.Android`

Had the same issue, this resolved it, thanks!
