### ISSUE TITLE
[Proposal] Table of Contents

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui-samples#194]
Thinking about how we want to organize samples. Top level I created a "6.0" folder for .NET 6 which matches what Blazor Samples does. Or it could be "Samples" or "src". Keeping the root clean is my main goal there.

I expect there will primarily be 2 kinds of samples here:
* Demo apps such as WeatherTwentyOne and Control Gallery
* Fundamentals apps such as you would find referenced by documentation

How about organization like this?

```
/6.0
  /Apps
  /App Builder
  /App Lifecycle
  /Behaviors
  /Controls
    /BoxView
    /Button
    ...
  /DataBinding
  /DependencyInjection
  /Effects
  /Layouts
    /AbsoluteLayout
    /CustomLayout
    /FlexLayout
    /Grid
    /RelativeLayout
    /StackLayout
```

**Comment by davidortinau** [comment]
@jongalloway @jamesmontemagno thoughts before I start dumping more and more in here?

**Comment by jamesmontemagno** [comment]
I am not 100% sure if 6.0 is necessary... like will things change in 7.0? do we need to copy stuff in there. My thoughts would be replace '6.0' with 'src' :)

**Comment by jamesmontemagno** [comment]
After seeing what blazor does let's just follow that

**Comment by jamesmontemagno** [comment]
@danroth27 thoughts?
