### ISSUE TITLE
Animation Sample Project  [Unable to Run]

### ISSUE THREAD

**Issue by DeepWorksStudios** [dotnet/maui-samples#205]
Cant run the project it says those 2 errors nomatter what i do (did clean the project & full rebuild)

Severity Code Description Project File Line Suppression State
Error PRI175: 0x80073b0f - Processing Resources failed with error: Doppelter Eintrag. Animations C:\Users\Sliem\Downloads\maui-samples-main\6.0\Animations\Animations\WINAPPSDKGENERATEPROJECTPRIFILE 1

Severity Code Description Project File Line Suppression State
Error PRI222: 0x80073b0f - Unspecified error occurred. Animations C:\Users\Sliem\Downloads\maui-samples-main\6.0\Animations\Animations\WINAPPSDKGENERATEPROJECTPRIFILE 1

Steps to Reproduce
Install VS2022 Preview with Maui
Download Sample Project
Open Maui Project named Animation
Start / Compile

Version with bug
6.0 (current)

Last version that worked well
Unknown/Other

Affected platforms
iOS, Android, Windows, macOS

Affected platform versions
Win 10.0.19041.0

Did you find any workaround?
No

Relevant log output: added as txt

[outputlog.txt](https://github.com/dotnet/maui-samples/files/8867547/outputlog.txt)

**Comment by VladislavAntonyuk** [comment]
check your .NET MAUI version

**Comment by DeepWorksStudios** [comment]
its all upto date 
double checked everything

**Comment by he1a2s0** [comment]
Same issue, I upgraded the version of library "CommunityToolkit.Maui" to `1.0.0` and it works, hope this can help you.

**Comment by DeepWorksStudios** [comment]
Still issue not resolved and i grabed your fix already sadly i did not help in my case
[buildlog.txt](https://github.com/dotnet/maui-samples/files/8888440/buildlog.txt)

**Comment by DeepWorksStudios** [comment]
Sadly still unresloved after reinstall windows and vs 2022 and maui worklo
[log build.txt](https://github.com/dotnet/maui-samples/files/8939208/log.build.txt)
ad :&/´

**Comment by micampbell** [comment]
I have the same error.

**Comment by davefxy** [comment]
I just downloaded the Animation sample, updated the CommunityToolkit.Maui to the latest version and the app ran fine on windows 11.
