### ISSUE TITLE
Appflyout Template Android&Windows Issuhe

### ISSUE THREAD

**Issue by DeepWorksStudios** [dotnet/maui-samples#207]
On windows it can start but as soon i select a flyout it breaks 
![image](https://user-images.githubusercontent.com/59297046/173294658-0878d93c-33e8-473d-8131-0ec9209434a8.png)
On Andrioid i cant even build it
![image](https://user-images.githubusercontent.com/59297046/173294932-006e2891-77d1-4e64-b966-7cc8d4030aca.png)
[buildlog android.txt](https://github.com/dotnet/maui-samples/files/8888574/buildlog.android.txt)

**Comment by VladislavAntonyuk** [comment]
Your path is too long.
https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later

**Comment by DeepWorksStudios** [comment]
Thanks for the hint in the following day i will try to fix it with your hint.
Will keep you updated
