### ISSUE TITLE
Typo/Bug in InvokePlatformCodeDemos

### ISSUE THREAD

**Issue by jasells** [dotnet/maui-samples#225]
I noticed a small bug in one of the demos.  I can push a branch for a fix.

Here is the issue (`deviceOrientationService1` was copy-pasted instead of `deviceOrientationService2` variable name, i think):
[Link to repo source](https://github.com/dotnet/maui-samples/blob/fddfb7b9bba71e95eb068cf08264d48753da0e6d/6.0/PlatformIntegration/InvokePlatformCodeDemos/InvokePlatformCodeDemos/MainPage.xaml.cs#L23).
```
        var deviceOrientationService1 = new ConditionalCompilationDeviceOrientationService();
        DeviceOrientation orientation1 = deviceOrientationService1.GetOrientation();
        conditionalCompilationOrientationLabel.Text = orientation1.ToString();

        var deviceOrientationService2 = new PartialMethodsDeviceOrientationService();
        DeviceOrientation orientation2 = deviceOrientationService1.GetOrientation();
        partialMethodsOrientationLabel.Text = orientation2.ToString();    
```

**Comment by davidbritch** [comment]
Closed by https://github.com/dotnet/maui-samples/pull/226
