### ISSUE TITLE
AzureDevOps Restore package error

### ISSUE THREAD

**Issue by BeautifulPilgrim** [dotnet/maui-samples#234]
**Few days ago It still work, but in 2022.7.7 GMT+8 9:02 I find it didn't work.**
In AzureDevOps **Restore package**  Stage, it reported that:

D:\a\1\s\BeautifulGate\BeautifulGate.csproj : error NU1102: Unable to find package Microsoft.Android.Runtime.33.android-arm with version (= 32.0.439)
D:\a\1\s\BeautifulGate\BeautifulGate.csproj : error NU1102:   - Found 6 version(s) in nuget.org [ Nearest version: 32.0.415 ]
D:\a\1\s\BeautifulGate\BeautifulGate.csproj : error NU1102:   - Found 0 version(s) in C:\hostedtoolcache\windows\dotnet\library-packs
D:\a\1\s\BeautifulGate\BeautifulGate.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
D:\a\1\s\BeautifulGate\BeautifulGate.csproj : error NU1102: Unable to find package Microsoft.Android.Runtime.33.android-arm64 with version (= 32.0.439)
D:\a\1\s\BeautifulGate\BeautifulGate.csproj : error NU1102:   - Found 6 version(s) in nuget.org [ Nearest version: 32.0.415 ]
D:\a\1\s\BeautifulGate\BeautifulGate.csproj : error NU1102:   - Found 0 version(s) in C:\hostedtoolcache\windows\dotnet\library-packs
D:\a\1\s\BeautifulGate\BeautifulGate.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
D:\a\1\s\BeautifulGate\BeautifulGate.csproj : error NU1102: Unable to find package Microsoft.Android.Runtime.33.android-x86 with version (= 32.0.439)
D:\a\1\s\BeautifulGate\BeautifulGate.csproj : error NU1102:   - Found 6 version(s) in nuget.org [ Nearest version: 32.0.415 ]
D:\a\1\s\BeautifulGate\BeautifulGate.csproj : error NU1102:   - Found 0 version(s) in C:\hostedtoolcache\windows\dotnet\library-packs
D:\a\1\s\BeautifulGate\BeautifulGate.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
D:\a\1\s\BeautifulGate\BeautifulGate.csproj : error NU1102: Unable to find package Microsoft.Android.Runtime.33.android-x64 with version (= 32.0.439)
D:\a\1\s\BeautifulGate\BeautifulGate.csproj : error NU1102:   - Found 6 version(s) in nuget.org [ Nearest version: 32.0.415 ]
D:\a\1\s\BeautifulGate\BeautifulGate.csproj : error NU1102:   - Found 0 version(s) in C:\hostedtoolcache\windows\dotnet\library-packs
D:\a\1\s\BeautifulGate\BeautifulGate.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages

But when I find in **Install MAUI** Stage, the package is that:

Writing workload pack installation record for Microsoft.Android.Runtime.32.android-arm version 32.0.438...
Installing pack Microsoft.Android.Runtime.32.android-arm64 version 32.0.438...
Writing workload pack installation record for Microsoft.Android.Runtime.32.android-arm64 version 32.0.438...
Installing pack Microsoft.Android.Runtime.32.android-x86 version 32.0.438...
Writing workload pack installation record for Microsoft.Android.Runtime.32.android-x86 version 32.0.438...
Installing pack Microsoft.Android.Runtime.32.android-x64 version 32.0.438...
Writing workload pack installation record for Microsoft.Android.Runtime.32.android-x64 version 32.0.438...

the difference is that:
Microsoft.Android.Runtime.33.android-arm with version (= 32.0.439)
Microsoft.Android.Runtime.32.android-arm version 32.0.438

so how can I fix it?

**Comment by RogueJin** [comment]
have the same issue, any work around here?
