### ISSUE TITLE
ListViewDemos: no footer on Android?

### ISSUE THREAD

**Issue by krishermans** [dotnet/maui-samples#242]
Hello!

First of all: thank you for providing these nice examples for learning MAUI! I was trying out ListViewDemos and noticed that footers don’t show up on Android (they do on Windows). I’m using an emulator and e.g. on TextHeaderFooterPage the footer is not visible.

Is this a known issue?

regards
Kris

**Comment by davidbritch** [comment]
Hi @krishermans 

It's a known issue to me that `ListView` footers don't appear on Android, but it looks like there isn't an issue for it in the [engineering repo](https://github.com/dotnet/maui). If you're able to create an issue there, it would be much appreciated!
