### ISSUE TITLE
Radio Button content Image is not setting correctly

### ISSUE THREAD

**Issue by praveenmohanmm** [dotnet/maui-samples#243]
Image is not rendering as a content
![image](https://user-images.githubusercontent.com/14816309/181541779-b6e73ba7-157d-46b5-adf1-bbcb9b275eca.png)

**Comment by davidbritch** [comment]
Hi @praveenmohanmm 

If you look at the [doc](https://docs.microsoft.comdotnet/maui/user-interface/controls/radiobutton) you'll see that:

- When the RadioButton.Content is assigned a View, it will be displayed on supported platforms (iOS, Windows), while unsupported platforms will fallback to a string representation of the View object (Android). In both cases, the content is displayed horizontally aligned next to the radio button circle.

So Android can't display an `Image` as the value of a `RadioButton`, unless you set a `ControlTemplate` for it.
