### ISSUE TITLE
Build error in VideoDemo - 'IDispatcherTimer' could not be found 

### ISSUE THREAD

**Issue by kjpou1** [dotnet/maui-samples#256]
The following error is encountered when trying to build [CreateHandlerDemo](https://github.com/dotnet/maui-samples/tree/main/6.0/UserInterface/Handlers/CreateHandlerDemo)

```
maui/maui-samples/6.0/UserInterface/Handlers/CreateHandlerDemo/VideoDemos/Controls/Video.cs(9,9): Error CS0246: The type or namespace name 'IDispatcherTimer' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (VideoDemos)
```

**Comment by jfversluis** [comment]
I think this should be fixed by now. Thanks for the report and the PR though! Much appreciated.
