### ISSUE TITLE
Is CarouselView on Windows not recommanded (yet?) ?

### ISSUE THREAD

**Issue by elTRexx** [dotnet/maui-samples#260]
Hi, I'm experiencing with MAUI, especially with CarouselView. I struggle with it since the behavior seems  to work on the emulated Android device, but not entirely on Windows Machine. (See my other subject [here](https://github.com/dotnet/maui/issues/9457) and [there](https://stackoverflow.com/questions/73355750/carousel-indicatorview-doesnt-automatically-update-on-windows-while-scrolling?noredirect=1#comment129595147_73355750)).
I tested with your MAUI sample project CarouselViewDemos and same issue on Windows Machine.
For example the Indicator example, when running on Windows Machine, doesn't update the Indicator while I'm scrolling through Carousel's items with my mouse wheel.

**Comment by plettb** [comment]
Frankly I'm starting to wonder whether _Maui_ should be recommended at this point!  I've been struggling with "CarouselView" since the preview versions, and now we're way past the "official" release and it's _still_ very buggy and practically useless, at least on Windows.  Given that Maui has 1,828 open issues as of this writing, I keep wondering when this product will _actually_ be ready for production use.

There is even a lovely "official" [demo app](https://github.com/dotnet/maui-samples/tree/main/6.0/UserInterface/Views/CarouselViewDemos) available for CarouselView, and that, too, has major problems when run on Windows.

Sorry - I realize this post is not helpful.  I'm just commiserating. :)

**Comment by githubgoucho** [comment]
**even not helpful and not working on window net7.0-windows10.0.19041.0**

Here is my setup:

Microsoft Visual Studio Community 2022
Version 17.5.4
VisualStudio.17.Release/17.5.4+33530.505
Microsoft .NET Framework
Version 4.8.04084

Installierte Version: Community

Visual C++ 2022   00482-90000-00000-AA200
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.5.318.41597
ASP.NET and Web Tools

Azure App Service-Tools v3.0.0   17.5.318.41597
Azure App Service-Tools v3.0.0

C#-Tools   4.5.2-3.23171.7+d17f741546fad2786cbd6394d08619544e53a36d
C#-Komponenten, die in der IDE verwendet werden. Abhängig von Ihrem Projekttyp und den zugehörigen Einstellungen kann eine andere Version des Compilers verwendet werden.

Extensibility Message Bus   1.4.3 (main@2a4517a)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.5.9 (11975e6)
Support for debugging Mono processes with Visual Studio.

NuGet-Paket-Manager   6.5.0
NuGet-Paket-Manager in Visual Studio. Weitere Informationen zu NuGet finden Sie unter https://docs.nuget.org/.

Razor (ASP.NET Core)   17.5.2.2316603+9f1b6856460af1e592d387ebef416eadddac453f
Stellt Sprachdienste für ASP.NET Core Razor bereit.

TypeScript-Tools   17.0.20105.2003
TypeScript-Tools für Microsoft Visual Studio

Visual Basic-Tools   4.5.2-3.23171.7+d17f741546fad2786cbd6394d08619544e53a36d
Visual Basic-Komponenten, die in der IDE verwendet werden. Abhängig von Ihrem Projekttyp und den zugehörigen Einstellungen kann eine andere Version des Compilers verwendet werden.

Visual F# Tools   17.5.0-beta.23053.5+794b7c259d9646a7eb685dad865aa27da7940a21
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
KI-gestützte Entwicklung für Visual Studio.

VisualStudio.DeviceLog   1.0
Informationen zum Paket

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage-Erweiterung   1.0
Detaillierte Informationen zur VSPackage Visual Studio-Erweiterung

Xamarin   17.5.0.173 (d17-5@33e727c)
Visual Studio-Erweiterung, um Entwicklung für Xamarin.iOS und Xamarin.Android zu ermöglichen.

Xamarin Designer   17.5.3.46 (remotes/origin/d17-5@e4dd80b2bb)
Visual Studio-Erweiterung zum Aktivieren der Xamarin Designer-Tools in Visual Studio.

Xamarin.Android SDK   13.2.0.0 (d17-5/797e2e1)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 6dd9def
    Java.Interop: xamarin/java.interop/main@149d70fe
    SQLite: xamarin/sqlite/3.40.0@fdc1e34
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@9f02d77

**Comment by jfversluis** [comment]
I don't think this repository is the right place to discuss whether a control is recommend or not. Please have a look at the Discussions tab on the .NET MAUI repository. This repo is for the sample applications here and any suggestions or issues you might have with that. Thanks!
