### ISSUE TITLE
When is the "Grid" VisualStateManager applied in the \Fundamentals\Shell\Xaminals sample

### ISSUE THREAD

**Issue by davefxy** [dotnet/maui-samples#261]
When is the "Grid" VisualStateManager applied in the \Fundamentals\Shell\Xaminals sample? On the pages on which the "Grid" VisualStateManager appears, there is no Grid control used.

**Comment by jfversluis** [comment]
More of a question than an actual issue with the sample and way old by now. Sorry this never got answered, I hope you found it somewhere else!
