### ISSUE TITLE
MAUI Shell search ItemTemplate not working

### ISSUE THREAD

**Issue by bearyung** [dotnet/maui-samples#269]
### Description

Xaminals (\maui-samples\6.0\Fundamentals\Shell\Xaminals) included the sample of custom handler (AnimalSearchHandler) but it does not work properly, here's the compiled output:

<img width="458" alt="image" src="https://user-images.githubusercontent.com/13907070/187064836-adaf0807-f3a4-4ce7-9796-913f99cc4b9a.png">

And this is the expected output quoted from the documentation:
![image](https://user-images.githubusercontent.com/13907070/187064845-e0cc5064-2800-4261-904a-130a20ea8e89.png)

[https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/shell/search](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/shell/search)

### Steps to Reproduce
Compile the \maui-samples\6.0\Fundamentals\Shell sample solution

### Version with bug
Version 17.3.1

### Last version that worked well
Unknown/Other

### Affected platforms
Windows 

### Affected platform versions

Windows 11 Pro (21H2)

### Did you find any workaround?

No

### Relevant log output

No response

**Comment by Legends** [comment]
Works under .net 8.0

**Comment by jfversluis** [comment]
Thanks for letting us know @Legends appreciate it!
