### ISSUE TITLE
Couldnt get maui-samples\7.0\UserInterface\Views\Map to compile

### ISSUE THREAD

**Issue by davefxy** [dotnet/maui-samples#275]
I updated VS 2022 to Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.4.0 Preview 2.1.
I performed a "dotnet workload restore". Got the following errors:

'The machine has a pending reboot. Installation will continue, but you may need to restart.
Downloading Microsoft.iOS.Sdk.Msi.x64 (15.4.1006-rc.1)
Workload installation failed. Rolling back installed packs...
Downloading microsoft.net.sdk.tvos.manifest-7.0.100-rc.1.msi.x64 (15.4.1006-rc.1)
Installation rollback failed: One or more errors occurred. (microsoft.net.sdk.tvos.manifest-7.0.100-rc.1.msi.x64::15.4.1006-rc.1 is not found in NuGet feeds https://api.nuget.org/v3/index.json;D:\Dev\Local-nuget-feed;C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\".)
Downloading microsoft.net.sdk.maccatalyst.manifest-7.0.100-rc.1.msi.x64 (15.4.1006-rc.1)
Installation rollback failed: One or more errors occurred. (microsoft.net.sdk.maccatalyst.manifest-7.0.100-rc.1.msi.x64::15.4.1006-rc.1 is not found in NuGet feeds https://api.nuget.org/v3/index.json;D:\Dev\Local-nuget-feed;C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\".)
Downloading microsoft.net.sdk.ios.manifest-7.0.100-rc.1.msi.x64 (15.4.1006-rc.1)
Installation rollback failed: One or more errors occurred. (microsoft.net.sdk.ios.manifest-7.0.100-rc.1.msi.x64::15.4.1006-rc.1 is not found in NuGet feeds https://api.nuget.org/v3/index.json;D:\Dev\Local-nuget-feed;C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\".)
Workload installation failed: One or more errors occurred. (microsoft.ios.sdk.msi.x64::15.4.1006-rc.1 is not found in NuGet feeds https://api.nuget.org/v3/index.json;D:\Dev\Local-nuget-feed;C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\".)
'
What can I do to fix this?

I eliminated all frameworks except.net7.0-android from the csproj file.
When trying to compile and run the Android version of app, one of the errors is
Error	NU1102	Unable to find package Microsoft.Maui.Controls.Maps with version (>= 7.0.0-rc.1.6687)
  - Found 1 version(s) in NuGetLocalServer [ Nearest version: 6.0.1857 ]
  - Found 1 version(s) in nuget.org [ Nearest version: 7.0.0-rc.1.6683 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  - Found 0 version(s) in C:\Program Files\dotnet\library-packs	MauiMaps	D:\Dev\Maui\MauiNet7\Map\MauiMaps\MauiMaps.csproj	1		Normal
  -'
If I change the Microsoft.Maui.Controls.Maps to version  7.0.0-rc.1.6683, it compiles on runs on an Android device.

**Comment by davidortinau** [comment]
Looks like I had a newer version referenced than what was shipped. I've updated the csproj to use 6683. Thx!

**Comment by davefxy** [comment]
If you have the time, could you answer questions about contributing to Maui Net 7.<![if !supportLists]>1.  <![endif]>I used ‘dotnet cake --target=VS --pack --sln="<download_directory>\MauiApp2\MauiApp2.sln’. But VS 2022 dpesnt show my Android device being available to test with.Is this the method to use if I want to step through Maui code to determine a problem cause.If I use ‘dotnet cake --target=VS, I cant compile and run the samples because I get a number of errors with the sample csprojs’ Sent from Mail for Windows From: David OrtinauSent: Tuesday, October 4, 2022 2:15 PMTo: dotnet/maui-samplesCc: Davefxy; AuthorSubject: Re: [dotnet/maui-samples] Couldnt get maui-samples\7.0\UserInterface\Views\Map to compile (Issue #275) Looks like I had a newer version referenced than what was shipped. I've updated the csproj to use 6683. Thx!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
