### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by MUNEERNIHAL** [dotnet/maui-samples#277]
The name 'InitializeComponent' does not exist in the current context	codesample (net6.0-android), codesample (net6.0-ios), codesample (net6.0-maccatalyst), codesample (net6.0-windows10.0.19041.0)	
![sample error](https://user-images.githubusercontent.com/32271852/192131985-a6a59f61-5866-4dbf-a017-0c6a7f922b24.PNG)

**Comment by davidortinau** [comment]
Looks like your project is using net6, and this is a net7 sample and feature. Install net7 RC1 or newer to run that.
