### ISSUE TITLE
Status Tray not displaying on Mac

### ISSUE THREAD

**Issue by ChrisAllisonMalta** [dotnet/maui-samples#284]
Hi Team, 
Not sure if I need to do something out of the box here (and I can't find any documentation on using the system tray) but I don't get a system tray icon on Mac Monterey 12.6. 

![Screenshot 2022-10-04 at 09 37 47](https://user-images.githubusercontent.com/11945453/193762205-ca9200ec-7891-4c0d-b0a1-c019f1205fd9.png)

**Comment by chucker** [comment]
Try clicking a few pixels to the left of your OneDrive icon. 😃

**Comment by ChrisAllisonMalta** [comment]
There you go!
