### ISSUE TITLE
dotnet 7 MauiMaps does not run on windows

### ISSUE THREAD

**Issue by dawg6** [dotnet/maui-samples#286]
I've tried running the dotnet7 MauiMaps sample on windows on multiple machines (windows 10 and windows 11) and it always fails with the following uncaught exception:

`Message = "Microsoft.UI.Xaml.Controls.Frame.NavigationFailed was unhandled."`

I've also tried updating to latest Maui public build 7.0.0-rc.2.11393.

**Comment by VladislavAntonyuk** [comment]
It is not supported. It will be a part of Community Toolkit
