### ISSUE TITLE
Advice: Upload sample/gallery to AppStore

### ISSUE THREAD

**Issue by xtuzy** [dotnet/maui-samples#297]
Today i see https://github.com/dotnet/maui/discussions/11208, i hope it can give developer more confidence.
A sample in Appstore will be a nice ad. Nobody want spend many time to download VisualStudio when they only want experience maui app.  You can find flutter have a [flutter gallery](https://play.google.com/store/apps/details?id=io.flutter.demo.gallery&hl=en&gl=US&pli=1) , winui have [winui gallery](https://apps.microsoft.com/store/detail/winui-3-gallery/9P3JFPWWDZRC) , Uno have Calculator(it is a worse example, i don't use uno because it show low performance). 
Another, you can get some feedback if maui have bug when run at some device.

**Comment by jfversluis** [comment]
Thank you for your advice! We have definitely though about this but we don't have any plans to do this in the near future.

**Comment by rilakuma123** [comment]
Was this closed intentionally? People interested in MAUI should be able to check it out easily before committing resources to it.
