### ISSUE TITLE
TabbedPage example crashes

### ISSUE THREAD

**Issue by eylvisaker** [dotnet/maui-samples#300]
I'm playing with the Controls Gallery (maui-samples\6.0\UserInterface\ControlGallery) and I noticed this issue. When running on Windows, the TabbedPage example crashes with an unhandled exception when I click the Green tab at the top. The exception has message "Value does not fall within the expected range." and a null StackTrace.

**Comment by jfversluis** [comment]
Can't reproduce anymore, I think this is fixed on the .NET MAUI side, thanks!
