### ISSUE TITLE
CollectionView not scrolling in Android nor Windows

### ISSUE THREAD

**Issue by DP-Technology-LLC** [dotnet/maui-samples#302]
### Description

In [CollectionViewDemos](https://github.com/dotnet/maui-samples/tree/main/6.0/UserInterface/Views/CollectionViewDemos), I copied and pasted the list of monkeys in VerticalListTextPage (the top option in MainPage) so there were 68 of them.

I am unable to scroll down to see the bottom of the list.

Also, nothing happens in the ScrollToByIndexPage when I tap on the button "Scroll to item 12".

### Steps to Reproduce

refer to Description

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/6.0/UserInterface/Views/CollectionViewDemos

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 8.0, Windows SDK 10.0.19041.0 (I think???)

**Comment by jfversluis** [comment]
Looks like this got resolved, thank you!
