### ISSUE TITLE
WorkingWithMaps gets exception with Windows and blank maps with Android

### ISSUE THREAD

**Issue by cdavidyoung** [dotnet/maui-samples#305]
I tested this with MacCatalyst and it seems to work perfectly.  I was trying to test with iOS but I can't get past the automatic provisioning, otherwise I assume it will work there.

I am using VS 2022 Preview with all the latest updates.  With my Android tablet running version 12 the app runs but the maps are blank.  With Windows it is getting an exception:

obj\Debug\net7.0-windows10.0.19041.0\win10-x64\Platforms\Windows\App.g.i.cs

            UnhandledException += (sender, e) =>
            {
                if (global::System.Diagnostics.Debugger.IsAttached) global::System.Diagnostics.Debugger.Break();
            };

**Comment by VladislavAntonyuk** [comment]
On Windows it is expected. Windows handler will be a part of .NET MAUI Community Toolkit. 

On Android please check your manifest file and make sure you are connected to the network

**Comment by cdavidyoung** [comment]
Well, the documentation (https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/appmodel/maps?view=net-maui-7.0&tabs=windows) does not mention this limitation.  We should at least catch it and print a friendly message.  I'll look into that.

I use the same Microsoft.Maui.Controls.Maps in my app in the same Android tablet and it works fine.  There is something wrong with the WorkingWithMaps app.  It also does not work in the Android simulator.  I'll try looking into this problem as well.

**Comment by cdavidyoung** [comment]
Well, I tried catching it in Views\Map\MapDemo\WorkingWithMaps\Views\MainPage.xaml.cs but the catch does not work.  "Microsoft.UI.Xaml.Controls.Frame.NavigationFailed was unhandled." cannot be caught there.

So I tried disabling the call for WinUI but I can't seem to use page.DisplayAlert nor Console.WriteLine to print a message.  Nothing appears.  Oh, well.

using Microsoft.Maui.Maps;
using System.Windows.Input;

namespace WorkingWithMaps.Views;

public partial class MainPage : ContentPage
{
    public ICommand NavigateCommand { get; set; }

    public MainPage()
    {
        InitializeComponent();

        NavigateCommand = new Command<Type>(async (Type pageType) =>
        {
            Page page = (Page)Activator.CreateInstance(pageType);
            if (DeviceInfo.Current.Platform != DevicePlatform.WinUI)
            {
                await Navigation.PushAsync(page);
            }
            else
            {
                Console.WriteLine($"Windows handler will be a part of .NET MAUI Community Toolkit.");
            }
            
        });

        BindingContext = this;
    }
}

**Comment by cdavidyoung** [comment]
Well, I can't use this nuget because I can't get past the Android blank map problem.  However, in studying the code I did learn how to launch the native Maps app on Windows.  Thanks!

**Comment by Gohico** [comment]
Hi, 

is there an ETA when the .NET MAUI Community Toolkit will release with the handler?
And I agree with - it would be nice to highlight this limitation a little in the documentation - although I understand that Marketing doesn't like that. But wasting engineering time is worse.

**Comment by jfversluis** [comment]
The Windows Maps implementation has been released as part of the .NET MAUI Community Toolkit & the documentation has been updated accordingly: https://learn.microsoft.com/dotnet/maui/user-interface/controls/map.

Android being blank is probably because you need to add your own API key as also described in the docs above.
