### ISSUE TITLE
Hamburger icon (Flyout Menu) does not actualize colors depending the theme of OS (Dark/Light) - Windows

### ISSUE THREAD

**Issue by leoderja** [dotnet/maui-samples#308]
### Description

This works well on Android, but on Windows, when you use **Dark theme** the button is correctly shown (see attached images), but when use **Light theme**, the horizontal lines can not been seen, because they have almost the same gray color that the background of the icon... This is problematic for the user, because he or she can not see the icon and back button...
![BackButtonLight](https://user-images.githubusercontent.com/5513105/208094730-e087b998-1d83-4829-b4ee-a1f992e9bfc9.png)

I have Win11 whit .NET 7.0.101. Visual Studio 17.4.3. Tested on Android: OK. Not tested on iOS.

### Steps to Reproduce

1. See this [MAUI Samples project.](https://github.com/dotnet/maui-samples).
2. Go to maui-samples\6.0\Fundamentals\Shell.
3.  Run Xaminals.sln.
![Flyout-HamburgueIc
![BackButtonLight](https://user-images.githubusercontent.com/5513105/208094687-10aeebd8-5642-4df9-91ff-a0d25603e3e3.png)
on_LightTheme_Win11](https://user-images.githubusercontent.com/5513105/207874087-da30fd47-8a6f-4598-90b4-f2890b8c040f.png)
![Flyout-HamburgueIcon_DarkTheme_Win11](https://user-images.githubusercontent.com/5513105/207874089-5c71a84a-b87b-4f99-8f5e-158ef8a2fc30.png)

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples.git

### Version with bug

6.0 Release Candidate 2 or older

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

Not yet

![BackButton](https://user-images.githubusercontent.com/5513105/208094464-b0955a50-f5ee-4859-ad1d-d870585a8b32.png)
![BackButtonLight](https://user-images.githubusercontent.com/5513105/208094776-52dcde6a-7b35-4ae6-a61f-a1f2a171f90b.png)

**Comment by PureWeen** [comment]
The Foreground color needs a dark theme value

https://github.com/dotnet/maui-samples/blob/768d9d0458dfc253fe436788afe31b9d46a198f4/6.0/Fundamentals/Shell/Xaminals/AppShell.xaml#L17

**Comment by leoderja** [comment]
Thank you PureWeen! Your answer has solved my problem and taught me a little more about MAUI...

**Comment by Richard-Dufour** [comment]
Thanks PureWeen, that has been driving me crazy for days.
