### ISSUE TITLE
Error on running the FlyoutSample application

### ISSUE THREAD

**Issue by acrigney** [dotnet/maui-samples#311]
When you select a flyout you get an unhandled exception.
Can't change IsPresented when setting Default

**Comment by svdhoogen** [comment]
Same here, stumbled upon this exception while migrating from a Xamarin app and thought the sample might provide some clarity, but it has the exact same exception...

**Comment by davidbritch** [comment]
Fixed by https://github.com/dotnet/maui-samples/pull/517
