### ISSUE TITLE
Out of date package references in TwoPaneView sample

### ISSUE THREAD

**Issue by spatialdude** [dotnet/maui-samples#321]
The **TwoPaneView** sample doesn't compile/work due to out of date RC package references.

Updating the references as below fixes the issue -

```xml
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="7.0.0" />
		<PackageReference Include="Microsoft.Maui.Controls.Foldable" Version="7.0.58" />
```

I've created a PR that updates these two packages to the current versions - https://github.com/dotnet/maui-samples/pull/320

**Comment by jfversluis** [comment]
Thanks for helping us out! Looks like this issue didn't get closed when the PR was merged, so doing that now 😄
