### ISSUE TITLE
Map Control MoveToRegion() doesn't work on Android

### ISSUE THREAD

**Issue by ChrisMacLeanRQI** [dotnet/maui-samples#343]
I have a .NET MAUII app that uses the Map control embedded in a page.  On page launch, I centre the map on the user's current location using the following code:

`Location position = new Location(currentLocation.Latitude, currentLocation.Longitude);
Distance dist = Distance.FromKilometers(30);
map.MoveToRegion(MapSpan.FromCenterAndRadius(position, dist));`

This does not work.  The Map control is visible, but the layer is not displayed.  The current location shows up, but the Map does not move to its location.

Here is the XAML code for the Map:

`<maps:Map x:Name="map" Grid.Row="1" HorizontalOptions="Fill" VerticalOptions="Fill" IsZoomEnabled="True" IsShowingUser="True">
<maps:Map.ItemTemplate>
<DataTemplate>
<maps:Pin Location="{Binding Position}" Address="{Binding Address}" Label="{Binding PlaceName}"/>
</DataTemplate>
</maps:Map.ItemTemplate>
</maps:Map>`

I have tested the app on both the Android Emulator as well as my Android Device running API 33.

I am running Visual Studio Professional 2022, Version 17.5.4

**Comment by ChrisMacLeanRQI** [comment]
I have conducted more debugging and found that the issue is when Navigating to an AppShell page through Shell.Current.GoToAsync() the Map will not execute the MoveToRegion() event.  If I navigate to the page through the AppShell TabBar, the MoveToRegion() works.

**Comment by jfversluis** [comment]
Thanks for providing the answer here!

I think this is more an issue in .NET MAUI than with the sample, it might be good to report this to the .NET MAUI repo next time so we can act on this faster and hopefully fix it for you soon. Glad you got it to work, thanks!
