### ISSUE TITLE
Listview demo project fails to show properly on ios

### ISSUE THREAD

**Issue by webwarrior06** [dotnet/maui-samples#346]
When I ran the listview project as it is, I encountered issues regarding rendering positions of the listview elements on the ios simulator.

![simulator_screenshot_6E6552B2-F4AF-48D5-A464-8EF5A1C29BD7](https://user-images.githubusercontent.com/3088750/236328471-51d5fe41-bbf8-4504-a9de-207d3833d00d.png)
![simulator_screenshot_AA2CD3CB-8E00-4B7B-98DB-F05C7EC28BAD](https://user-images.githubusercontent.com/3088750/236328594-60c5b699-e7fa-40da-ba85-55bf1d135f61.png)
![simulator_screenshot_BEA74B40-4399-4F49-87E1-72B0A86545F6](https://user-images.githubusercontent.com/3088750/236328700-72a7d3d7-8373-4ac8-b6c5-474eb93631a8.png)

What can be a solution to this?
Thanks!

**Comment by jfversluis** [comment]
This is a .NET MAUI product issue and not so much a sample issue. Also I think this has been resolved in recent versions so please try that!
