### ISSUE TITLE
Android : Memory leak with shadow on changing label

### ISSUE THREAD

**Issue by lionel-loscos** [dotnet/maui-samples#347]
I'm currently testing an app on differents android tablets, I have 2 labels to show date and time.
If I add a shadow property to these labels directly or from the style, I have a memory leak (the memory usage is growing each time the label showing current time is changing - each second) and the final result is a crash with an "outofmemory" warning.

for info : the 2 labels in my mainpage

        <Label Style="{StaticResource DateLabel}" VerticalTextAlignment="Center" HorizontalTextAlignment="Start" HorizontalOptions="Start" Text="{Binding Path=DateText}"/>
        <Label Style="{StaticResource TimeLabel}" VerticalTextAlignment="Center" HorizontalTextAlignment="End" HorizontalOptions="End" Text="{Binding Path=TimeText}"/>

and the styles in Styles.xaml (I'm using OnScreenSizeMarkup.Maui for dynamic adaptation)

    <Shadow x:Key="LabelShadow1" Brush="{StaticResource Black}"
                Offset="{markups:OnScreenSize Default='4,4',Large='4,4',ExtraLarge='16,16'}"
                Radius="{markups:OnScreenSize Default='4',Large='4',ExtraLarge='16'}"
                Opacity="{markups:OnScreenSize Default='0.3',Large='0.3',ExtraLarge='0.4'}"/>

    <Style x:Key="DateLabel" TargetType="{x:Type Label}">
        <Setter Property="TextColor" Value="{StaticResource DarkGreen}"/>
        <Setter Property="FontSize" Value="{markups:OnScreenSize Default='48',Large='48',ExtraLarge='184'}"/>
        <Setter Property="Padding" Value="{markups:OnScreenSize Default='8,0,0,0',Large='8,0,0,0',ExtraLarge='56,0,0,0'}"/>
        <Setter Property="VerticalOptions" Value="{markups:OnScreenSize Default='Start',Large='Start',ExtraLarge='Center'}"/>
        <Setter Property="FontAttributes" Value="Bold"/>
        <Setter Property="Shadow" Value="{DynamicResource LabelShadow1}"/>
    </Style>
    <Style x:Key="TimeLabel" TargetType="{x:Type Label}">
        <Setter Property="TextColor" Value="{StaticResource DarkRed}"/>
        <Setter Property="FontSize" Value="{markups:OnScreenSize Default='48',Large='48',ExtraLarge='184'}"/>
        <Setter Property="Padding" Value="{markups:OnScreenSize Default='0,0,8,0',Large='0,0,8,0',ExtraLarge='0,0,56,0'}"/>
        <Setter Property="VerticalOptions" Value="{markups:OnScreenSize Default='Start',Large='Start',ExtraLarge='Center'}"/>
        <Setter Property="FontAttributes" Value="Bold"/>
        <Setter Property="Shadow" Value="{DynamicResource LabelShadow1}"/>
    </Style>

**Comment by jfversluis** [comment]
This repo is just for the samples and this looks like you might want to report something for .NET MAUI. Please do so on the .NET MAUI repo. We have done a lot of work in terms of performance and especially memory leaks. You might want to check out the upcoming .NET 8 release that has all that.

Thanks!
