### ISSUE TITLE
Is it possible to perform multiple selections in the Collection View without the use of the Shift key in mac?

### ISSUE THREAD

**Issue by theRealGupta** [dotnet/maui-samples#364]
We have observed that it is possible to perform multiple selections in the collection view. However, in accordance with my specific requirement, I would like to inquire whether it is also feasible to achieve multiple selection without the need to press the shift key in mac.

**Comment by jfversluis** [comment]
That is not implemented in .NET MAUI right now so that won't work out of the box. You might be able to implement something yourself by customizing the CollectionView. More information on that can be found [here](https://learn.microsoft.com/dotnet/maui/user-interface/handlers/customize).
