### ISSUE TITLE
The OnIdiomDemoPage is not working on Windows.

### ISSUE THREAD

**Issue by rwecho** [dotnet/maui-samples#366]
No matter how we resize the windows the BoxView is always green

dotnet SDK: 8.0.100-preview.6.23330.14

**Comment by jfversluis** [comment]
I think you might be misunderstanding how `OnIdiom` works. This is not dependant on the size of the window. The idiom describes what type of device it is: desktop, tablet, phone, etc.

If we look at the code in this sample:

```xml
<BoxView x:Name="boxView"
         Color="{OnIdiom Phone=Red, Tablet=Green, Desktop=Blue}"
         WidthRequest="{OnIdiom Phone=200, Tablet=300, Desktop=400}"
         HeightRequest="{OnIdiom Phone=200, Tablet=300, Desktop=400}"
         HorizontalOptions="Center" />
```

On `Desktop` the `BoxView` will always be blue. If you run it on a `Tablet` it will be green and on a `Phone` red. Then additionally, for each of these idioms there will be a different height and width. Not to confuse with the width and height of the window.

I hope this clears it up!
