### ISSUE TITLE
Could not link native shared library

### ISSUE THREAD

**Issue by Transis-Felipe** [dotnet/maui-samples#367]
I'm trying to compile some of the samples projects, but I retrieve the error bellow:

Could not link native shared library

I'm already developing others projects made using MAUI

![image](https://github.com/dotnet/maui-samples/assets/4941173/b334b961-b36c-4599-a11c-71132711772b)

The error above is from the project \maui-samples-main\7.0\Beginners-Series\MauiApp2.sln

**Comment by jfversluis** [comment]
Can't reproduce with the current code and installation. I suspect something might've been wrong with your setup somehow. Hope you got it figured out by now!
