### ISSUE TITLE
Project doesn't load

### ISSUE THREAD

**Issue by santo998** [dotnet/maui-samples#373]
When I open the Localization solution, the project doesn't load and outputs this error:
'maui-samples-main\7.0\Fundamentals\Localization\LocalizationDemo\LocalizationDemo.csproj : error  : Duplicated folder item found in the project: "Platforms\Android\Resources\drawable-es\flag.png".'

**Comment by AugPav** [comment]
I have the same issue on Visual Studio 2022.
