### ISSUE TITLE
Ejemplos básicos 

### ISSUE THREAD

**Issue by hjosimar** [dotnet/maui-samples#378]

**Comment by drumset** [comment]
Aquí tienes para elegir:
https://github.com/dotnet/maui-samples/tree/main/7.0
Este para empezar te servirá:
https://github.com/dotnet/maui-samples/tree/main/7.0/Beginners-Series/MauiApp2

**Comment by jfversluis** [comment]
Not sure what you mean by this issue, sorry!

I think there are both basic and more extensive projects in this repository, you can browse them a bit easier through the online [Samples browser](https://learn.microsoft.com/samples/browse/?expanded=dotnet&products=dotnet-maui) if there is anything you'd like to see or doesn't look right, please let us know. Thanks!
