### ISSUE TITLE
Project does nothing!

### ISSUE THREAD

**Issue by santo998** [dotnet/maui-samples#385]
When I execute the code, it just open LocalizedPage, but button does nothing, even I don't have a way to change culture from within the app.
I find it useless as the only way to change culture would be changing my OS culture.
I would expect the project to have an option of changing culture and seeing it reflected in real time, or resetting the app, etc.

**Comment by jfversluis** [comment]
That is the point of this example since it also localizes the app name and such, that is not something that will work if you change it from within the app. Maybe this will help for translations within your app: https://youtu.be/IBz9Ku24ZGY

Thanks for the feedback!

**Comment by santo998** [comment]
Thank you so much!
This is awesome!
