### ISSUE TITLE
ListView rendering on Mac Catalyst is wrong

### ISSUE THREAD

**Issue by AllenD-MSFT** [dotnet/maui-samples#386]
I'm running the ListView demo solution and targeting Mac Catalyst. Most of the list view rendering is messed up:
![image](https://github.com/dotnet/maui-samples/assets/49214121/b381b947-aa40-4d9a-b86b-2fb7ef825d5d)

Seems either the sample needs to be adjusted or the MAUI SDK has an issue on Mac Catalyst.

**Comment by davidbritch** [comment]
It's equally a mess on iOS, but it's fine on Android. So it's more that it's a `ListView` problem in the SDK.
