### ISSUE TITLE
CarouselViewDemos on Win11 hangs after each test

### ISSUE THREAD

**Issue by githubgoucho** [dotnet/maui-samples#398]
build with VC 2022 V 17.8.1 .net 8

**Comment by jfversluis** [comment]
Hey @githubgoucho thanks for checking out the samples!

What do you mean exactly with after each test? You mean whenever you click a CarouselView option and go back? Does the application really hang or can you simply not select another option?

**Comment by githubgoucho** [comment]
yes, I have to restart the app each time.

**Comment by jfversluis** [comment]
Yep, confirmed! It works on Android, not on Windows. I _think_ it might be this: https://github.com/dotnet/maui/issues/18047

So lets keep our eye on that one and see if that resolves it for a future update. Thanks!
