### ISSUE TITLE
Xanimals iOS issue - unable to select first item on the ShellContent

### ISSUE THREAD

**Issue by manikanth** [dotnet/maui-samples#405]
https://github.com/dotnet/maui-samples/assets/1164175/6766863b-30d3-438f-9a92-1c102a96a074

Unable to select the first item on the FlyoutItem/ShellContent.

This happens only on the iOS

**Comment by manikanth** [comment]
The issue is with the ShellFlyout Header, request @davidortinau to please look at it!

**Comment by manikanth** [comment]
Request @jfversluis to look at this please.

**Comment by jfversluis** [comment]
Will have a look but that will be in the new year 😊

**Comment by wolfgangschneider** [comment]
same issue- any workaround?

**Comment by manikanth** [comment]
> same issue- any workaround?

The only thing I can do, is moved my user name to the footer (which looks really bad). Waiting to hear from dev folks, didn't know it is taking this long!

**Comment by wolfgangschneider** [comment]
Another Workaround:
Add a Dummy entry on top:

<ShellContent  IsVisible="{OnPlatform false,iOS='true'}"    ContentTemplate="{DataTemplate controls:Info}" Route="**nowhere**"/>

**Comment by manikanth** [comment]
Thanks for the help, appreciate it.

Its been more than a month, asking for help! 
(Now it is getting difficult to convince Ops team to migrate Xamarin to MAUI, with such delays)

**Comment by jfversluis** [comment]
@manikanth while I appreciate your situation, please note that you are asking here on a samples repository. This isn't a official support channel for .NET MAUI, no one is actively monitoring here for issues. The samples are provided as-is to help you learn a concept and support the Microsoft Learn website.

**Comment by manikanth** [comment]
Thanks for the reply, I get the idea on this now. This was more of a core feature, as we usually show the user details on the header. Kinda surprised to see this not work and had to opt for workarounds.

Again, thanks for all the support.

**Comment by jfversluis** [comment]
@manikanth which is probably a bug in the .NET MAUI SDK then. And that team is not monitoring this repository. So while this sample might show the bug, it's then maybe a bug in .NET MAUI and should be reported there or it probably already is. Going to add a pinned issue to make this more clear for the next person. Thanks!

**Comment by manikanth** [comment]
Yea it appears to be a bug in the MAUI SDK.

I did find the issue [here](https://github.com/dotnet/maui/issues/19712)
