### ISSUE TITLE
.NET 8 samples do not run on Mac OS 13.6.3 Ventura. Require Mac OS 14 Sonoma

### ISSUE THREAD

**Issue by iWhacko** [dotnet/maui-samples#417]
I downloaded the latest Samples to use as a base project for a simple project I want to try. 
I updated to .NET 8 because this samples project has no branches or tags for .net7 versions.

After updating my system to use .NET8 I can get the PointOFSale example to build using maccatalyst. But it does not run.

The resulting binaries require MacOS 14 Sonoma. I have tried to set the target framework to a lower version, but nothing seems to work. And I do not want to install a beta version of my OS just to run a sample.

Any tips? i have provided the project here: https://github.com/iWhacko/PointOfSale it should compile fine. 

please let me know if you require any additional information.

**Comment by iWhacko** [comment]
I feel so stupid. I tried a fresh sample again and it worked, seems one of the nuget packages was causing it but did not throw any errors. 
Apparently the latest EntityCoreFramework 8.x.x is always building for MacOS 14.x.

**Comment by jfversluis** [comment]
Glad you figured it out @iWhacko !
