### ISSUE TITLE
why are all sample codes not running because of packages?

### ISSUE THREAD

**Issue by giwonseoneolab** [dotnet/maui-samples#444]
what should I do to open and build those?

**Comment by jfversluis** [comment]
I'm sorry I'm not sure what you mean? All samples should be runnable on your local machine if you have .NET 8 installed with the .NET MAUI workload and all prerequisites.

**Comment by giwonseoneolab** [comment]
![스크린샷 2024-02-28 오전 9 30 52](https://github.com/dotnet/maui-samples/assets/152831609/8d3ad64a-6bf4-480c-9270-be71eedfed18)
I installed .net 8.0 and checked it by typing .net version in my terminal. Still, it's not opened.

**Comment by jfversluis** [comment]
It looks like you're using Visual Studio for Mac which officially does not have support for .NET 8 as it will be retired in August 2024. If you want to build this on a Mac either use the command-line or VS Code.
