### ISSUE TITLE
DatePicker crashes app

### ISSUE THREAD

**Issue by Workings** [dotnet/maui-samples#456]
Was wondering if was just my own app, but when tried your sample app showed same behaviour. On iOS 17.4.

**Comment by jfversluis** [comment]
You're probably using Xcode 15.3 which isn't supported right now: https://github.com/dotnet/maui/issues/21057

**Comment by Workings** [comment]
Thanks. Any idea when will be supported?

**Comment by jfversluis** [comment]
Unfortunately not, sorry!
