### ISSUE TITLE
WEATHER APP DOES NOT RUN!!

### ISSUE THREAD

**Issue by TheRealKraytonian** [dotnet/maui-samples#458]
![image](https://github.com/dotnet/maui-samples/assets/60334798/4bcf1ce9-47e7-4e70-9e31-1565cdb30a6b)

**Comment by jfversluis** [comment]
I think the real error is not the macos SDK, but the message after that which is truncated: androidtargetSdkVersion 31 is less than....?

You might want to look into your Android SDK setup and try again!

**Comment by jfversluis** [comment]
No response so assuming you figured out how to do this. Closing this now.
