### ISSUE TITLE
Push notifications sample

### ISSUE THREAD

**Issue by davidbritch** [dotnet/maui-samples#489]
Write a sample that demonstrates/explains how to use Azure Notification Hubs via a backend service, to send push notifications to .NET MAUI Android and iOS apps.

An ASP.NET Web API backend will be used to handle device registration on behalf of the client, via the Notification Hubs SDK for backend operations.

A  .NET MAUI app for Android and iOS will demonstrate the use of the backend service using explicit register/deregister actions. This will largely involve writing native code using .NET for Android and .NET for iOS. Push notifications should appear in notification centre when the app is stopped or in the background. If a notification contains an action and is received when the app is in the foreground, or when a notification is used to launch the app from notification centre, a message will be presented identifying the action specified.

The technologies involved will be:

- Azure Notification Hubs
- Azure App Service
- Apple Push Notification Service
- Firebase Cloud Messaging
- ASP.NET Web API
- .NET MAUI
- .NET for Android
- .NET for iOS

---
[Associated WorkItem - 273380](https://dev.azure.com/msft-skilling/Content/_workitems/edit/273380)

**Comment by VladislavAntonyuk** [comment]
https://vladislavantonyuk.github.io/articles/.NET-MAUI-Push-Notifications-using-Azure-Notification-Hub.-Part-1.-Setup-Azure-Notification-Hub/
