### ISSUE TITLE
iOS App Randomly Crashing with Memory Leak During Large Data Load, Navigation, and Save Operations

### ISSUE THREAD

**Issue by rahulrthor07** [dotnet/maui-samples#537]
Our .NET MAUI iOS application crashes randomly when handling large collections of data, saving data, and performing navigation actions. The issue persists even with .NET 9 preview, where memory usage spikes, leading to out-of-memory (OOM) errors and suspected memory leaks.

Steps to Reproduce:

Load a large collection of data into a ListView or CollectionView(also tried with Syncfusion SFListview).
Navigate between pages while keeping the large data collection in memory.
Save data or perform operations on the collection.
After repeated navigation or data operations, observe increased memory usage, leading to eventual app crashes.
Expected Behaviour:

The app should handle large data sets, navigation, and data-saving operations without causing memory issues or crashes.
Actual Behaviour:

Random app crashes occur during data load, save, or navigation.
Memory usage increases consistently without being released, eventually causing OOM errors.
Environment:

.NET MAUI Version: .NET 9 Preview
IDE: Visual Studio 2022 for Mac (or Windows, specify if applicable)
Device/Simulator: iOS 16+ (specify device model if on physical device)

**Comment by jfversluis** [comment]
I don't think this is the right repository for that. This is just for hosting .NET MAUI samples, not the actual .NET MAUI SDK product. you probably want to report something on https://github.com/dotnet/maui

Thanks!
