### ISSUE TITLE
PinType not changing the icon

### ISSUE THREAD

**Issue by AngeloLazzari** [dotnet/maui-samples#555]
The pinType is not working, I mean: the same icon is showing for PinType.generic or PinType.Place.

I took your app semple and i changed the values for pins in the PinPage as showed but the result is the same icon showed for both of them...
![Image](https://github.com/user-attachments/assets/9c0f270d-fb66-499c-99ab-51c4c5d3890d)

This tested on Iphone 15 IOS 17.5 simulator, cannot test on android because is not loading the map...
![Image](https://github.com/user-attachments/assets/7ef04e07-fdd8-4e8f-b058-4d25fdf83e43)

I created a repro project to replicate the issue: https://github.com/AngeloLazzari/MauiMapExample/tree/main/MapDemo

Thank you 
Angelo

**Comment by jfversluis** [comment]
As indicated in [the documentation](https://learn.microsoft.com/dotnet/maui/user-interface/controls/map#pin-types):

> However, setting the Pin.Type property to any PinType member does not change the appearance of the rendered pin. Instead, you must customize the Pin handler to customize pin appearance.
