### ISSUE TITLE
Android workload for Linux

### ISSUE THREAD

**Issue by knuxbbs** [dotnet/maui-samples#61]
So, there isn't an Android workload for Linux?

I understand that it may be difficult to bring iOS support to Linux, but what prevents you from bringing an Android workload?

Is that in the plans? Should I wait for the next releases?

Thanks in advance.

**Comment by jonathanpeppers** [comment]
We don't have Linux packages yet for Android. I'm not sure when those will be available.

You could try it right now if you built xamarin-android from source:

https://github.com/xamarin/xamarin-android/blob/master/Documentation/building/unix/instructions.md#creating-a-local-net-6-workload

One our engineers uses Linux primarily, so they've always kept our Linux support working.

**Comment by pablojimpas** [comment]
@jonathanpeppers any news on this topic? are mobile workloads expected to support Linux for the final .NET 6 release?

**Comment by jonathanpeppers** [comment]
I don't think there are plans to have official support for Android on Linux in .NET 6. This would be the Microsoft.Android.Sdk.Linux package we aren't pushing anywhere at the moment.

Perhaps we could put this on a nightly feed so it could be used, however?

The idea being you could add this to a `NuGet.config` on Linux:

```xml
 <add key="xamarin" value="https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json" />
 ```

Then do `dotnet workload install microsoft-android-sdk-full`.

We'll keep this in mind, as it might be useful.

**Comment by knuxbbs** [comment]
The nightly builds would be very appreciated by the community, I guess.

**Comment by webczat** [comment]
that's rather unexpected tbh there is nothing official rn. I wouldn't expect this to be related to no linux support in maui, unless it isn't.

**Comment by rokups** [comment]
Any news on nightlies? I would love to start migrating my software from a mono+.net framework 4.x combo to .net6.
