### ISSUE TITLE
(macOS pkg for) iOS workload doesn't include sentinel

### ISSUE THREAD

**Issue by chucker** [dotnet/maui-samples#67]
(Related: #47)

I'm not sure if this is by design, but the Android workload adds a `.sentinel` file to `./sdk/`, and the iOS one doesn't:

![image](https://user-images.githubusercontent.com/20194/108824807-727f9080-75c2-11eb-8d32-6e4af93be239.png)

Consequently, **only** installing the SDK and the iOS workload will result in the "The target platform identifier ios was not recognized" error.

If this is intended, the README should make it clearer that building the iOS sample on macOS will fail unless you *also* install the Android workload.

**Comment by jonathanpeppers** [comment]
We are hoping the need for a `.sentinel` file at all can go away.

The dotnet/sdk did this so they could ship workload support behind a feature flag in .NET 5. I think they can get rid of it soon.

**Comment by jonathanpeppers** [comment]
In .NET 6 Preview 4, `EnableWorkloadResolver.sentinel` is no longer needed.
